//! Imports - DO NOT EDIT THIS FILES
import Header from "./DO_NOT_EDIT/Header";
import PokemonStatProgressBar from "./DO_NOT_EDIT/PokemonStatProgressBar";
import PokemonTypeBadge from "./DO_NOT_EDIT/PokemonTypeBadge";
import pokemonData from "./example.json";

function App() {
  return (
    <main>
      <div className="bg-blue-900 pb-8 pt-16">
        <Header />
        {/* Inputs */}
        <div className="mx-auto max-w-4xl px-4 flex flex-col md:flex-row md:justify-between items-center  gap-3">
          {/* Search Field and Button */}
          <div className="flex w-full md:w-2/3 shadow-md">
            <input
              type="text"
              className="border-yellow-500 border-2 p-2 w-full rounded-l-xl h-12 md:h-16"
              placeholder="Type name or number (eg. Bulbasaur, 35)"
            />
            <button className="bg-yellow-500 text-white px-4 hover:bg-yellow-600 rounded-r-xl  uppercase font-bold">
              Search
            </button>
          </div>

          <p className="text-white "> - OR - </p>

          {/* Get Random Pokemon Button */}
          <button className="bg-red-600 hover:bg-red-700 text-white py-2 px-6 rounded-xl h-12 md:h-16 uppercase font-bold shadow-md">
            Get Random
          </button>
        </div>
      </div>

      <div className="mx-auto max-w-4xl px-4 my-10 ">
        {/* Pokemon Data */}
        <div className="grid grid-cols-2 md:grid-cols-4 md:grid-rows-6 gap-2">
          <div className="row-span-1 row-start-1 col-span-1 bg-white border-4 border-blue-400 shadow shadow-blue-300 py-2 px-4 rounded-lg flex items-center">
            <h3 className="text-xl uppercase font-bold">{pokemonData.name}</h3>
          </div>
          <div className="row-span-1 row-start-1 col-span-1 bg-white border-4 border-blue-400 shadow shadow-blue-300  py-2 px-4 rounded-lg flex items-center">
            <h3 className="text-lg font-bold">#{pokemonData.id}</h3>
          </div>

          <div className="row-start-2 row-span-4  col-span-2 bg-white border-4 border-blue-400 shadow shadow-blue-300 py-2 px-4 rounded-lg flex justify-center">
            <img
              src={pokemonData.sprites.front_default}
              alt={pokemonData.name}
              className="object-cover w-40 md:h-full md:w-auto"
            />
          </div>

          <div className="row-start-6 row-span-1 col-start-1 col-span-2 bg-white border-4 border-blue-400 shadow shadow-blue-300  py-2 px-4 rounded-lg flex items-center justify-center gap-2">
            {pokemonData.types.map(({ type }) => (
              <PokemonTypeBadge type={type.name} />
            ))}
          </div>

          <div className="col-span-2 md:row-start-2 md:row-span-full bg-white border-4 border-blue-400 shadow shadow-blue-300 py-2 px-4  rounded-lg ">
            <h4 className="text-lg font-bold mb-4">Stats:</h4>
            {pokemonData.stats.map(({ base_stat, stat }) => (
              <PokemonStatProgressBar statName={stat.name} baseStat={base_stat} />
            ))}
          </div>
        </div>
      </div>
    </main>
  );
}

export default App;
